
const loans = [
  {
    loanId: 1,
    firstName: 'ojo',
    lastName: 'oladimeji',
    email: 'deji@gmail.com',
    address: 'no 2',
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    status: 'pending',
    balance: 20000,
    interest: 1000,
  },
  {
    loanId: 2,
    firstName: 'emi',
    lastName: 'oladimejijdj',
    email: 'deimiji@gmail.com',
    address: 'no 3',
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    status: 'pending',
    balance: 20000,
    interest: 1000,
  },
  {
    loanId: 3,
    user: 'dayo@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: false,
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    balance: 10500,
    interest: 1000,
  },
  {
    loanId: 4,
    user: 'victor@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: false,
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    balance: 10500,
    interest: 1000,
  },
  {
    loanId: 5,
    user: 'dayo@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: true,
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    balance: 0,
    interest: 1000,
  },
  {
    loanId: 6,
    user: 'dayo@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: true,
    tenor: 2,
    amount: 20000,
    paymentInstallment: 10500,
    balance: 0,
    interest: 1000,
  },
];


export default loans;
